version: "3.7"

services:
  app:
    image: docker.pkg.github.com/yahyaabdurr/item-app/item-app:v1
    ports:
      - 80:8080

    depends_on:
      - item-db

    restart: always

  item-db:
    image: mongo:3

    volumes:
      - app-db:/data/db

volumes:
  app-db:
